#GRIP : The Sparks Foundation ( Data Science and Business Analytics Intern )

Name: Divyank Mahalle

Task 6: Prediction using Supervised Machine Learning (classification algorithm) by Decision Tree Algorithm( ML ).

● Create the Decision Tree classifier and visualize it graphically.
● The purpose is if we feed any new data to this classifier, it would be able to predict the right class accordingly.

In this task We can solve this by using supervised machine learning classification algorithm.Decision tree is used for both classification and regression.we are loading iris flower datasets using sklearn library. In the output we can see that the shape of data is (150, 4) which means we have 150 samples (rows)and 4 features (columns).

4 features are : sepal length , sepal width, petal length , petal width. The features have some values (150 sample) based on that flowers classified in three category that is setosa ,versicolor and virginica (0,1 and 2).On the basis of features () we will decide which flower belongs to which category by training the model with the datasets that we have.

We know that by definition decision tree is a tree shaped flowchart-like structure (reversed tree) with nodes (leaf), branches and decision making conditions.

Iris Datasets:Iris is a family of flower which contains three type of flower called setosa ,versicolor and Virginica.

Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Importing Dataset

In [ ]:
df=pd.read_csv('Iris_Task_6.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Classifying data in Dependent and Independent Variable

In [ ]:
X = df.iloc[:,1:5].values
y = df.iloc[:, -1].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)  #Data is splitted in 70%Training Data and 30% Test dataset

##Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-1.02366372 -2.37846268 -0.18295039 -0.29145882]
 [ 0.69517462 -0.10190314  0.93066067  0.73721938]
 [ 0.92435306  0.58106472  1.04202177  1.6373128 ]
 [ 0.1222285  -1.92315077  0.6522579   0.35146505]
 [ 0.92435306 -1.24018291  1.09770233  0.73721938]
 [-0.33612839 -1.24018291  0.03977182 -0.16287405]
 [ 2.07024529 -0.10190314  1.26474398  1.38014325]
 [ 0.46599617  0.58106472  0.48521625  0.48004983]
 [-0.45071761 -1.46783886 -0.01590873 -0.16287405]
 [ 0.46599617 -0.784871    0.59657735  0.73721938]
 [ 0.46599617 -0.55721505  0.70793846  0.35146505]
 [-1.13825295 -1.24018291  0.37385514  0.6086346 ]
 [ 0.46599617 -1.24018291  0.6522579   0.86580415]
 [ 1.26812073  0.35340877  0.48521625  0.22288028]
 [ 0.69517462 -0.10190314  0.76361901  0.99438893]
 [ 0.1222285   0.80872067  0.37385514  0.48004983]
 [-1.25284217  0.12575281 -1.24088089 -1.32013702]
 [-0.10694994 -0.784871    0.70793846  0.86580415]
 [-0.33612839 -0.784871    0.20681348  0.0942955 ]
 [-0.33612839 -0.32955909 -0.12

In [ ]:
print(X_test)

[[-0.10694994 -0.55721505  0.70793846  1.50872803]
 [ 0.1222285  -1.92315077  0.09545238 -0.29145882]
 [-0.45071761  2.6299683  -1.35224199 -1.32013702]
 [ 1.6118884  -0.32955909  1.37610509  0.73721938]
 [-1.02366372  0.80872067 -1.29656144 -1.32013702]
 [ 0.46599617  0.58106472  1.20906343  1.6373128 ]
 [-1.02366372  1.03637663 -1.40792255 -1.19155225]
 [ 0.92435306  0.12575281  0.48521625  0.35146505]
 [ 1.03894229 -0.55721505  0.5408968   0.22288028]
 [ 0.23681773 -0.55721505  0.09545238  0.0942955 ]
 [ 0.23681773 -1.01252695  0.98634122  0.22288028]
 [ 0.5805854   0.35340877  0.37385514  0.35146505]
 [ 0.23681773 -0.55721505  0.48521625 -0.03428927]
 [ 0.69517462 -0.55721505  0.42953569  0.35146505]
 [ 0.23681773 -0.32955909  0.48521625  0.22288028]
 [-1.13825295  0.12575281 -1.29656144 -1.4487218 ]
 [ 0.1222285  -0.32955909  0.37385514  0.35146505]
 [-0.45071761 -1.01252695  0.31817459 -0.03428927]
 [-1.25284217 -0.10190314 -1.35224199 -1.19155225]
 [-0.56530683  1.94700044 -1.40

## Training the Decision Tree Classification model on the Training set



In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

##Predicting a new result


In [ ]:
print(classifier.predict(sc.transform([[6.1,2.1,4.5,2.2]])))

['Iris-virginica']


##Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']


##Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)   #We got 97 percent accuracy when we split data 70/30 Train/Test split.

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


0.9777777777777777

**Thank you,The Sparks Foundation**
